### ISSUE TITLE
DMA2 interrupts missing

### ISSUE THREAD

**Issue by skibon02** [kossnikita/at32f4xx-pac#2]
For some reason, DMA2 interrupts (specifically for at32f437) are not exposed

I have modified device.x file which includes missing symbols:
```
PROVIDE(DMA2_CHANNEL1 = DefaultHandler);
PROVIDE(DMA2_CHANNEL2 = DefaultHandler);
PROVIDE(DMA2_CHANNEL3 = DefaultHandler);
PROVIDE(DMA2_CHANNEL4 = DefaultHandler);
PROVIDE(DMA2_CHANNEL5 = DefaultHandler);
PROVIDE(DMA2_CHANNEL6 = DefaultHandler);
PROVIDE(DMA2_CHANNEL7 = DefaultHandler);
```
And some modifications at src/at32f437/mod.rs to introduce DMA2_CHANNELX related stuff. 

After applying these changes it started working for me, but the better way should be to modify SVD file or to add yaml patches which I am not familiar with.

**Comment by kossnikita** [comment]
Yes, yet another bug in SVD.
According to the manual, Artery has channels 0 to 6, not 1 to 7. Is there a reason to name them that way?
![image](https://github.com/user-attachments/assets/4aa556b9-a56d-4259-877d-40f75b7cbf2c)

UPD: Okay. It is.
![image](https://github.com/user-attachments/assets/f504839e-1174-4e5c-bb47-7a7effc3f253)

**Comment by kossnikita** [comment]
Fixed with 1e1d2c6
@skibon02 please update pac and verify

**Comment by skibon02** [comment]
my build is broken on your latest commit from master.

I got a lot of errors, mostly on `variant()` calls
[errors.txt](https://github.com/user-attachments/files/16931464/errors.txt)

**Comment by kossnikita** [comment]
Use `variant` method only with enum . For bits use `bits`.

**Comment by skibon02** [comment]
I can modify my code, but the thing is, this is a breaking change and I guess we should increase minor version
Because two commits earlier works fine with my code

**Comment by kossnikita** [comment]
Since svd2rust changed the minor version, pac should change the version too. This makes sense.
As for `variant` and `bits`, this was in older versions too. There was no check that `variant` is an enum. Formally, you used the method incorrectly, there was no error.

**Comment by skibon02** [comment]
Yip, works fine now
Thanks!
